# Setup
title:            Seth Neller
tagline:          Home
description:      Asst. Prof. of Economics <br/> University of Tennessee <br/> seth.neller@gmail.com
url:              https://sethneller.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Seth Neller'
  url:            https://twitter.com/sethneller

github:
  repo:           https://github.com/sethneller/sethneller.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

